# Generated by Django 4.1 on 2024-06-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geopoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Polygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_id", models.PositiveSmallIntegerField(verbose_name="Сектор")),
                ("bottom_left_x", models.FloatField()),
                ("upper_left_x", models.FloatField()),
                ("upper_right_x", models.FloatField()),
                ("bottom_right_x", models.FloatField()),
                ("bottom_left_y", models.FloatField()),
                ("upper_left_y", models.FloatField()),
                ("upper_right_y", models.FloatField()),
                ("bottom_right_y", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="WaterMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ice_coef", models.FloatField()),
                (
                    "ice_category",
                    models.CharField(
                        choices=[
                            (
                                "L",
                                "(Высокая проходимость) Высокий интегральный коэффициент",
                            ),
                            (
                                "M",
                                "(Средняя проходимость) Средний интегральный коэффициент",
                            ),
                            (
                                "S",
                                "(Низкая проходимость) Низкий интегральный коэффициент",
                            ),
                        ],
                        default="S",
                        max_length=20,
                    ),
                ),
                (
                    "sector_id",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="map",
                        to="maps.polygon",
                        verbose_name="Сектор",
                    ),
                ),
            ],
        ),
    ]
