# Generated by Django 4.1 on 2024-06-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="polygon",
            name="lat",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="polygon",
            name="lon",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
