# Generated by Django 4.1 on 2024-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_polygon_lat_polygon_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolygonNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.JSONField()),
            ],
        ),
    ]
