# Generated by Django 4.1 on 2024-06-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "location_point",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maps.geopoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NotAssigned", "Не определено"),
                            ("Ice1", "Легкое судно (1)"),
                            ("Ice2", "Легкое судно (2)"),
                            ("Ice3", "Легкое судно (3)"),
                            ("Arc4", "Среднее судно (4)"),
                            ("Arc5", "Среднее судно (5)"),
                            ("Arc6", "Среднее судно (6)"),
                            ("Arc7", "Среднее судно (7)"),
                            ("Arc8", "Среднее судно (8)"),
                            ("Arc91", "Ледокол (91)"),
                            ("Arc92", "Ледокол (92)"),
                        ],
                        default="NotAssigned",
                        max_length=20,
                    ),
                ),
                ("max_speed", models.FloatField()),
                (
                    "location_point",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maps.geopoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Дата размещения заявки",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        null=True, verbose_name="Дата начала маршрута"
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        null=True, verbose_name="Дата окончания маршрута"
                    ),
                ),
                (
                    "active",
                    models.CharField(
                        choices=[("ACT", "Актуальная"), ("OLD", "Исполненная")],
                        max_length=15,
                    ),
                ),
                (
                    "destination_point",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="route_requests_end",
                        to="smp.port",
                        verbose_name="Порт назначения",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="route_requests",
                        to="smp.ship",
                        verbose_name="Судно",
                    ),
                ),
                (
                    "start_point",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="route_requests_start",
                        to="smp.port",
                        verbose_name="Порт отправления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрутная заявка",
                "verbose_name_plural": "Маршрутные заявки",
                "ordering": ("-pub_date",),
            },
        ),
        migrations.AddConstraint(
            model_name="routerequest",
            constraint=models.UniqueConstraint(
                fields=("ship", "start_point", "date_start"), name="unique_ship_start"
            ),
        ),
    ]
